------------------------------------[BestSeller HELP]
function bsShowHelp(msg)
  sml_print(JFCC.."------------------------------------------------------------------------")
  sml_print(JFCC.."Best Seller "..bsVersion.." by Smashed / Bladefist --- Help:")
  sml_print(JFCC.."/bs show (or hide)..........shows or hides interface")
  sml_print(JFCC.."/bs minishow (or minihide)..displays minimap button")
  sml_print(JFCC.."/bs rs...............restack items in backpacks")
  sml_print(JFCC.."/bs aslist...........lists items that are on your Auto Sell list")
  sml_print(JFCC.."/bs asremove #.......removes an item from the auto sell list")
  sml_print(JFCC.."/bs asadd <item>.....adds an item (by name) to the auto sell list")
  sml_print(JFCC.."/bs asthresh <#>.....sets threshold for auto sell "..RFCC.."(USE WITH CAUTION!!!)")
  sml_print(JFCC.."             Where # is one of the following:")
  sml_print(JFCC.."              "..DFCC.."0=Poor"..WFCC.." 1=Normal"..GFCC.." 2=Uncommon"..BFCC.." 3=Rare"..PFCC.." 4=Epic"..OFCC.." 5=Legendary")
  sml_print(JFCC.."              Example: /bs asthresh 2 (will auto sell all Uncommon (GREEN) and lower items)")
  sml_print(JFCC.."/bs aselist..........lists items to be excluded from auto sell")
  sml_print(JFCC.."/bs aseremove #......removes an item from the auto sell exclusion list")
  sml_print(JFCC.."/bs aseadd <item>....adds an item (by name) to the auto sell exclusion list")
  sml_print(JFCC.."------------------------------------------------------------------------")
end 
